# Generated by Django 4.2.4 on 2023-09-01 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0002_alter_advertisement_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='upc',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
