# Generated by Django 4.2.4 on 2023-09-01 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0003_advertisement_upc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adv_category', to='advertisement.category'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adv_image', to='advertisement.advertisementimage'),
        ),
    ]
