# Generated by Django 4.2.4 on 2023-10-24 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0007_alter_advertisement_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisementimage',
            name='advertisement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='advertisement.advertisement'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='upc',
            field=models.BigIntegerField(default=224, unique=True, verbose_name='upc'),
        ),
        migrations.AlterField(
            model_name='advertisementimage',
            name='image',
            field=models.ImageField(upload_to='advertisements/'),
        ),
    ]
