# Generated by Django 4.2.4 on 2023-10-26 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('advertisement', '0008_advertisementimage_advertisement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='upc',
            field=models.BigIntegerField(default=635, unique=True, verbose_name='upc'),
        ),
    ]
